### ISSUE TITLE
Original code reference or at the very least author mentioned

### ISSUE THREAD

**Issue by iOrange** [arkytik/4A-Engine-Blender#1]
Hi!

First of all - I always welcome more tools for the Metro games!
But it would be nice to at least mention the origin of the code.
The model/skeleton code looks VERY familiar, even enums have the exact same names, and structures/fields names and overall organization.
I don't mind if someone is using MetroEX/MetroTools code, but at least mention of that would be nice.

Thanks.

**Comment by arkytik** [comment]
Дремлет хлопец у дороги, снятся хлопцу перемоги. А автор кода - Modera

**Comment by arkytik** [comment]
> Hi!
> 
> First of all - I always welcome more tools for the Metro games! But it would be nice to at least mention the origin of the code. The model/skeleton code looks VERY familiar, even enums have the exact same names, and structures/fields names and overall organization. I don't mind if someone is using MetroEX/MetroTools code, but at least mention of that would be nice.
> 
> Thanks.

Дремлет хлопец у дороги, снятся хлопцу перемоги. А весь код я писал и он мой - авторский, а структуры форматов я посмотрел у Modera.

**Comment by iOrange** [comment]
Well, I guess continuing on a nice Modera's tradition of just stealing code and pretending it's their? 

Just a few simple examples, can do more if not enough.
At the very least try to not copy my comments to make it less "visible" :)

![image](https://github.com/arkytik/4A-Engine-Blender/assets/7016607/e8ca2977-4e3b-4390-b2fe-25c3dc1b6378)
![image](https://github.com/arkytik/4A-Engine-Blender/assets/7016607/59348dd5-4eac-4932-a300-c928108aea27)
![image](https://github.com/arkytik/4A-Engine-Blender/assets/7016607/ed4e96ae-8e60-487f-a6aa-171ce8c22d61)

**Comment by iOrange** [comment]
Oh, and Skeleton reading is 1-to-1 code from MetroEX btw, you just can't deny that, Modera's one is very basic and is missing tons of stuff, and you even copied my approach with "structures read themselves using stream"

**Comment by arkytik** [comment]
Ты думаешь мне западло указать, что я взял чей-то код? Мне очень много пришлось самому додумать, особенно cform... Ты заявляешь, что моего труда тут нет и ты полноценный разработчик всего, но это не так, более того, я в рот ебал дальше помогать аудитории метро разработчиков... Я укажу тебя автором, если ты сделаешь репозиторий MetroTools снова публичным

**Comment by iOrange** [comment]
First of all - nowhere did I say "I wrote it all!". I've just pointed out to parts of code that I recognize. Especially in Skeleton reading - that is my style - streams that do the base types, and all the derived/composed types do implement "Serialize" method so that you serialize class and it can serialize all of its members recursively.  You've adopted that approach here, basically translating my Skeleton code into python.

Now you're saying "open MetroTools" repo, but that's why it is private now again - I've got tired of people stealing code without any acknowledgement.

I've been digging Metro formats since 2010, which is easily traceable on gamedev.ru forum, and everything including Modera's code (at least for the archives/textures/models/skeletons/levels) is based on that. Zero acknowledgement!

That's why I said "f**k it! I'm done!". It basically became a new Stalker toxic community of "everyone ~~steals~~ borrows from other, makes their own "solyanka" and calls it a day".

You do what you want. It was just a kind ask to provide references to the original code. I'm fine without.

Good luck.

**Comment by arkytik** [comment]
Добре! Упомянул тебя, с новым апдейтом укажу тебя, как одного из авторов... Это обидно, когда воруют код и не указывают авторство, все выше - было лишь моей шуткой! Но я также буду рад, если ты дашь доступ к MetroTools, чтобы выход обновления был ускорен
